### ISSUE TITLE
Error setting up integration

### ISSUE THREAD

**Issue by zoezoevp** [Pigotka/ha-cc-jablotron-cloud#24]
Hi,

After updating to HA Core 2024.9.2, the integration broke.  I tried to delete the integration and reinstall, but it returns an error during setup.  All worked fine before.  Unfortunately, a roll back to 2024.9.1 doesn't fix it.

Thanks for helping,

Manu

Unexpected exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/requests/models.py", line 974, in json
    return complexjson.loads(self.text, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/simplejson/__init__.py", line 514, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/simplejson/decoder.py", line 386, in decode
    obj, end = self.raw_decode(s)
               ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/simplejson/decoder.py", line 416, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/jablotron_cloud/config_flow.py", line 59, in async_step_user
    info = await validate_input(self.hass, user_input)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/jablotron_cloud/config_flow.py", line 34, in validate_input
    await hass.async_add_executor_job(hub.get_session_id)
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/jablotronpy/jablotronpy.py", line 91, in get_session_id
    status, data = self._make_request(
                   ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/jablotronpy/jablotronpy.py", line 69, in _make_request
    data = r.json()
           ^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/requests/models.py", line 978, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by Pigotka** [comment]
I have not updated to 24.9.2 yet but it looks like some changes happened in config flow of HA itself. I recommend to delete the integration and install it again. It should enforce new conflig flow recreation. If that won't help it think you will have to manually remove the record.

**Comment by zoezoevp** [comment]
Deleting and re-installing did not help.

**Comment by Pigotka** [comment]
Actually I have the same error on my own installation and it started yesterday. The problem is not with the integration but with Jablotron servers itself. We will look into it with @fdegier maybe API got updated.

**Comment by Pigotka** [comment]
It's up again for me. Can you reload and check @zoezoevp ?

**Comment by zoezoevp** [comment]
After removing and reinstalling, it still doesn't work.

2024-09-18 15:57:12.527 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration jablotron_cloud which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-09-18 16:00:04.056 WARNING (ImportExecutor_0) [homeassistant.backports.enum] StrEnum was used from jablotron_cloud, this is a deprecated alias which will be removed in HA Core 2025.5. Use enum.StrEnum instead, please report it to the author of the 'jablotron_cloud' custom integration
2024-09-18 16:00:32.402 WARNING (ImportExecutor_0) [homeassistant.const] TEMP_CELSIUS was used from jablotron_cloud, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfTemperature.CELSIUS instead, please report it to the author of the 'jablotron_cloud' custom integration
2024-09-18 16:00:32.447 ERROR (MainThread) [homeassistant.components.binary_sensor] Error while setting up jablotron_cloud platform for binary_sensor
File "/config/custom_components/jablotron_cloud/binary_sensor.py", line 38, in async_setup_entry
2024-09-18 16:00:32.456 ERROR (MainThread) [homeassistant.components.switch] Error while setting up jablotron_cloud platform for switch
File "/config/custom_components/jablotron_cloud/switch.py", line 39, in async_setup_entry

**Comment by Pigotka** [comment]
Yesterday I updated to 24.9.2 and integration works fine. So I do not think your problem is related with new version of HA.
Try to enable debug logging and reinstall your integration and post the HA log file.

**Comment by FilemonCZ** [comment]
i still cannot fix this 

Logger: jablotronpy.jablotronpy
Zdroj: /usr/local/lib/python3.12/site-packages/jablotronpy/jablotronpy.py:74
První výskyt: 14:03:52 (384 výskyty)
Naposledy logováno: 16:25:27

An unexpected error occurred, status code: 404, response: {'http-code': 404, 'errors': [{'code': 'FUNCTION.NOT-FOUND', 'message': ''}], 'meta': {'display-type': 'TOAST'}, 'sentry-error-id': '63d239fd768045b78cd1fb10ef9d95cc'}, {"http-code":404,"errors":[{"code":"FUNCTION.NOT-FOUND","message":""}],"meta":{"display-type":"TOAST"},"sentry-error-id":"63d239fd768045b78cd1fb10ef9d95cc"}
An unexpected error occurred, status code: 404, response: {'http-code': 404, 'errors': [{'code': 'FUNCTION.NOT-FOUND', 'message': ''}], 'meta': {'display-type': 'TOAST'}, 'sentry-error-id': 'f80db4f8c1954b9f888f3b8a32e90492'}, {"http-code":404,"errors":[{"code":"FUNCTION.NOT-FOUND","message":""}],"meta":{"display-type":"TOAST"},"sentry-error-id":"f80db4f8c1954b9f888f3b8a32e90492"}
An unexpected error occurred, status code: 404, response: {'http-code': 404, 'errors': [{'code': 'FUNCTION.NOT-FOUND', 'message': ''}], 'meta': {'display-type': 'TOAST'}, 'sentry-error-id': '11ff9a0ce375480a8ec6c227ececb7f2'}, {"http-code":404,"errors":[{"code":"FUNCTION.NOT-FOUND","message":""}],"meta":{"display-type":"TOAST"},"sentry-error-id":"11ff9a0ce375480a8ec6c227ececb7f2"}
An unexpected error occurred, status code: 404, response: {'http-code': 404, 'errors': [{'code': 'FUNCTION.NOT-FOUND', 'message': ''}], 'meta': {'display-type': 'TOAST'}, 'sentry-error-id': '9b66615f95b847729799435f5894211e'}, {"http-code":404,"errors":[{"code":"FUNCTION.NOT-FOUND","message":""}],"meta":{"display-type":"TOAST"},"sentry-error-id":"9b66615f95b847729799435f5894211e"}
An unexpected error occurred, status code: 404, response: {'http-code': 404, 'errors': [{'code': 'FUNCTION.NOT-FOUND', 'message': ''}], 'meta': {'display-type': 'TOAST'}, 'sentry-error-id': 'c3236d506089435eb4d1d0b6fb1aafa9'}, {"http-code":404,"errors":[{"code":"FUNCTION.NOT-FOUND","message":""}],"meta":{"display-type":"TOAST"},"sentry-error-id":"c3236d506089435eb4d1d0b6fb1aafa9"}


Tato chyba pochází z vlastní integrace.

Logger: custom_components.jablotron_cloud
Zdroj: helpers/update_coordinator.py:354
integrace: Jablotron Cloud (dokumentace, problémy)
První výskyt: 14:03:58 (96 výskyty)
Naposledy logováno: 16:25:27

Unexpected error fetching Jablotron Cloud data
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 354, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/jablotron_cloud/__init__.py", line 135, in _async_update_data
    gates = await self.hass.async_add_executor_job(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/jablotronpy/jablotronpy.py", line 264, in get_programmable_gates
    status, data = self._make_request(
                   ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/jablotronpy/jablotronpy.py", line 83, in _make_request
    return self._make_request(end_point=end_point, headers=headers, payload=payload, retry=retry)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/jablotronpy/jablotronpy.py", line 83, in _make_request
    return self._make_request(end_point=end_point, headers=headers, payload=payload, retry=retry)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/jablotronpy/jablotronpy.py", line 83, in _make_request
    return self._make_request(end_point=end_point, headers=headers, payload=payload, retry=retry)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/jablotronpy/jablotronpy.py", line 77, in _make_request
    logger.error(f"Exhausted all retry options, response: {data.json()}")
                                                           ^^^^^^^^^
AttributeError: 'dict' object has no attribute 'json'


what i can also see is that in HACS is version 0.6.2 and after installing fresh new version ingration say 0.6.1 

please help me..

**Comment by zoezoevp** [comment]
After some time (couple of hours), it spontaneously started to work again for me.
