### ISSUE TITLE
arm throws error 

### ISSUE THREAD

**Issue by voipmonitor** [Pigotka/ha-cc-jablotron-cloud#27]
Whem arming any section - it throws error: (disarm works) - how to debug this? Where might be problem? 

2024-10-17 17:09:12.560 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140204570625472] Unexpected exception
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 239, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2738, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2779, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 975, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1047, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/alarm_control_panel/__init__.py", line 191, in async_alarm_arm_away
    await self.hass.async_add_executor_job(self.alarm_arm_away, code)
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/jablotron_cloud/alarm_control_panel.py", line 172, in alarm_arm_away
    self.coordinator.bridge.control_component(
  File "/usr/local/lib/python3.12/site-packages/jablotronpy/jablotronpy.py", line 368, in control_component
    raise UnexpectedResponse("Unable to control component")
jablotronpy.jablotronpy.UnexpectedResponse: Unable to control component

**Comment by Pigotka** [comment]
Idk, the error is reported not from the integration but from jablotronPy library. Maybe you have your PIN wrong? :o)
I can fix the error handling in the integration to show proper error but since it is your local issue I can't help you with that.

**Comment by voipmonitor** [comment]
I have figured out where is the problem. My jablotron has some errors like battery gone in smoke sensor and one keyboard. Thus if I arm the zone in the jablotron android app - it says it is blocked and there is 10 seconds counter or extra button which forces the zone lock but eventually it locks. Maybe this corner case would be nice to handle in this integration? Would you like to debug it and add support for this case?

**Comment by fdegier** [comment]
> I have figured out where is the problem. My jablotron has some errors like battery gone in smoke sensor and one keyboard. Thus if I arm the zone in the jablotron android app - it says it is blocked and there is 10 seconds counter or extra button which forces the zone lock but eventually it locks. Maybe this corner case would be nice to handle in this integration? Would you like to debug it and add support for this case?

From the API this is possible, but it would need an option whether users want this or not. @Pigotka I will add support for this in JablotronPy.

**Comment by fdegier** [comment]
@Pigotka version 0.6.4 has been released which allows force argument, if set to true, it will bypass the warnings from Jablotron.

**Comment by voipmonitor** [comment]
how long does it take when I can see the 0.6.4 version in HACS?

**Comment by fdegier** [comment]
> how long does it take when I can see the 0.6.4 version in HACS? 

0.6.4 is never appearing in HACS as it's the library used by this plugin.

**Comment by Pigotka** [comment]
I can update to new jablotronpy immediately but I'm not sure it is the right choice to always arm using force option. Having proper solution with user option would be better but it would take mi some time to add.

**Comment by fdegier** [comment]
> I can update to new jablotronpy immediately but I'm not sure it is the right choice to always arm using force option. Having proper solution with user option would be better but it would take mi some time to add.
> 
> 

I agree, it should be an option or noted. That being said, it would be better to force than to error.

**Comment by voipmonitor** [comment]
when I press button on web browser on jablotron cloud: 

section=STATE_5&status=1&code=XXXX&uid=STATE_5_prehled

result: 

 "ts": 1729526924,
    "id": "STATE_5",
    "authorization": 200,
    "result": 1162,
    "responseCode": 200
    
    then the browser sends another request: 
    
jablonet.net/app/ja100/ajax/getBypassedPeriphery.php

section=STATE_5&code=XXXX

response: 

{"count":1,"responseCode":200,"peripheries":[{"section":4,"bypas":"
<b>
    \u00dast\u0159edna<\/b>(Fault)"}],"load":false}


and there is 10 seconds timer in the UI which I can skip or just wait which will send another request to: 

https://www.jablonet.net/app/ja100/ajax/ovladani2.php

payload: section=STATE_5&status=4&code=XXXX&uid=STATE_5_prehled

response: 

 "ts": 1729526935,
    "id": "STATE_5",
    "authorization": 200,
    "result": 1,
    "responseCode": 200
}

**Comment by fdegier** [comment]
Good research, but whatever you upgraded is not enough. 1) JablotronPy dependency needs to be bumped and 2) the force (bypass) needs to be (optionally) set to true 

Then it will work. 

What you can also do is in your Jablotron central set bypass to bypass without confirmation

**Comment by voipmonitor** [comment]
I have double checked version of the jablontronpy /usr/local/lib/python3.12/site-packages/jablotronpy/jablotronpy.py and it has the latest force option (which I have manually changed to the true in this file to be sure its effective but it still throws the same error: 

Failed to call service script/toggle_alarm_sauna_domek. Unable to control component, response: {'control-errors': [{'component-id': 'SEC-37249065', 'control-error': 'BYPASS-TIMED'}], 'states': [{'component-id': 'SEC-1427687', 'state': 'DISARM'}, {'component-id': 'SEC-1427688', 'state': 'DISARM'}, {'component-id': 'SEC-1467819', 'state': 'ARM'}, {'component-id': 'SEC-1580819', 'state': 'DISARM'}, {'component-id': 'SEC-37249065', 'state': 'DISARM'}]}

**Comment by Pigotka** [comment]
@fdegier he is right, I already released new version forcing it

**Comment by fdegier** [comment]
Oh I did not know. Sorry about that. 

It's weird that is doesn't bypass, in my tests it does and I've used this setting for over a year. What kind of device is blocking?

**Comment by Pigotka** [comment]
Btw. I had dead battery in the keyboard last month and integration was still working fine.

**Comment by fdegier** [comment]
> Btw. I had dead battery in the keyboard last month and integration was still working fine.

In Flink, did you configure bypass without confirmation?

**Comment by Pigotka** [comment]
Not consciously :)

út 22. 10. 2024 v 8:49 odesílatel Fred de Gier ***@***.***>
napsal:

**Comment by voipmonitor** [comment]
I do not know how to configure the bypass. In the meantime my new battery arrived and all is working now.
