### ISSUE TITLE
Issue when setting up

### ISSUE THREAD

**Issue by aimartin** [Pigotka/ha-cc-jablotron-cloud#28]
Hi!

I've tried to configure jablotron cloud in HomeAssistant 2024.10 and I'm getting the following:

2024-10-17 18:44:38.805 ERROR (SyncWorker_4) [jablotronpy.jablotronpy] An unexpected error occurred, status code: 404, response: {'http-code': 404, 'errors': [{'code': 'FUNCTION.NOT-FOUND', 'message': ''}], 'meta': {'display-type': 'TOAST'}, 'sentry-error-id': '9472595be4be424db45b2xxxxxxxxxxxx'}, {"http-code":404,"errors":[{"code":"FUNCTION.NOT-FOUND","message":""}],"meta":{"display-type":"TOAST"},"sentry-error-id":"9472595be4be424db45b2xxxxxxxxxxxx"}
2024-10-17 18:44:41.107 ERROR (SyncWorker_4) [jablotronpy.jablotronpy] An unexpected error occurred, status code: 404, response: {'http-code': 404, 'errors': [{'code': 'FUNCTION.NOT-FOUND', 'message': ''}], 'meta': {'display-type': 'TOAST'}, 'sentry-error-id': '9472595be4be424db45b2xxxxxxxxxxxx'}, {"http-code":404,"errors":[{"code":"FUNCTION.NOT-FOUND","message":""}],"meta":{"display-type":"TOAST"},"sentry-error-id":"9472595be4be424db45b2xxxxxxxxxxxx"}
2024-10-17 18:44:43.456 ERROR (SyncWorker_4) [jablotronpy.jablotronpy] An unexpected error occurred, status code: 404, response: {'http-code': 404, 'errors': [{'code': 'FUNCTION.NOT-FOUND', 'message': ''}], 'meta': {'display-type': 'TOAST'}, 'sentry-error-id': '9472595be4be424db45b2xxxxxxxxxxxx'}, {"http-code":404,"errors":[{"code":"FUNCTION.NOT-FOUND","message":""}],"meta":{"display-type":"TOAST"},"sentry-error-id":"9472595be4be424db45b2xxxxxxxxxxxx"}
2024-10-17 18:44:45.779 ERROR (SyncWorker_4) [jablotronpy.jablotronpy] An unexpected error occurred, status code: 404, response: {'http-code': 404, 'errors': [{'code': 'FUNCTION.NOT-FOUND', 'message': ''}], 'meta': {'display-type': 'TOAST'}, 'sentry-error-id': '9472595be4be424db45b2xxxxxxxxxxxx'}, {"http-code":404,"errors":[{"code":"FUNCTION.NOT-FOUND","message":""}],"meta":{"display-type":"TOAST"},"sentry-error-id":"9472595be4be424db45b2xxxxxxxxxxxx"}
2024-10-17 18:44:45.779 ERROR (MainThread) [custom_components.jablotron_cloud] Unexpected error fetching Jablotron Cloud data
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 354, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/jablotron_cloud/__init__.py", line 140, in _async_update_data
    gates = await self.hass.async_add_executor_job(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/jablotronpy/jablotronpy.py", line 264, in get_programmable_gates
    status, data = self._make_request(
                   ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/jablotronpy/jablotronpy.py", line 83, in _make_request
    return self._make_request(end_point=end_point, headers=headers, payload=payload, retry=retry)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/jablotronpy/jablotronpy.py", line 83, in _make_request
    return self._make_request(end_point=end_point, headers=headers, payload=payload, retry=retry)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/jablotronpy/jablotronpy.py", line 83, in _make_request
    return self._make_request(end_point=end_point, headers=headers, payload=payload, retry=retry)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/jablotronpy/jablotronpy.py", line 77, in _make_request
    logger.error(f"Exhausted all retry options, response: {data.json()}")
                                                           ^^^^^^^^^
AttributeError: 'dict' object has no attribute 'json'

I can connect and control my alarm through https://www.jablonet.net/, and I'm sure that credentials are correct (I tried with wrong credentials and I get 401 in logs). Am I doing something wrong? Is there anything else I need to enable somewhere?

**Comment by Pigotka** [comment]
No update, closing.
