### ISSUE TITLE
Issue with arming/disarming from Apple Home

### ISSUE THREAD

**Issue by JakubBW** [Pigotka/ha-cc-jablotron-cloud#33]
I have a problem when I try to arming or disarming in the Apple Home application interace.
Anyone know how to solve this problem?

Log below:

Rejestrator: homeassistant.core
Źródło: core.py:2822
Pierwsze zdarzenie: 20:27:03 (1 zdarzenia)
Ostatnio zalogowany: 20:27:03

Error executing service: <ServiceCall alarm_control_panel.alarm_arm_away (c:01JDANF5KM2DF2G19A0K9HHG31): entity_id=['alarm_control_panel.dom_sypialnia']>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/core.py", line 2822, in _run_service_call_catch_exceptions
    await coro_or_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 2845, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1007, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1079, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/alarm_control_panel/__init__.py", line 316, in async_handle_alarm_arm_away
    await self.async_alarm_arm_away(self.check_code_arm_required(code))
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/alarm_control_panel/__init__.py", line 277, in check_code_arm_required
    raise ServiceValidationError(
homeassistant.exceptions.ServiceValidationError: Arming requires a code but none was given for alarm_control_panel.dom_sypialnia

**Comment by Faasteer** [comment]
Same problem here. Unfortunately, I don't know the solution. 😢

`Logger: homeassistant.core
Zdroj: core.py:2822
První výskyt: 07:18:11 (4 výskyty)
Naposledy logováno: 08:41:29

Error executing service: <ServiceCall alarm_control_panel.alarm_arm_away (c:01JE309WRPQVC7XXPZDZFKMCNM): entity_id=['alarm_control_panel.jablotron_ja_100_byt_komplet']>
Error executing service: <ServiceCall alarm_control_panel.alarm_arm_away (c:01JE30HYN3CFVJ8P5N8WFE9D70): entity_id=['alarm_control_panel.jablotron_ja_100_byt_komplet']>
Error executing service: <ServiceCall alarm_control_panel.alarm_arm_away (c:01JE34Z9C9P4Q28DFGETB2GZ4K): entity_id=['alarm_control_panel.jablotron_ja_100_byt_komplet']>
Error executing service: <ServiceCall alarm_control_panel.alarm_arm_away (c:01JE352E06NG0RCGJBCWJBFYYB): entity_id=['alarm_control_panel.jablotron_ja_100_byt_komplet']>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/core.py", line 2822, in _run_service_call_catch_exceptions
    await coro_or_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 2845, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1007, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1079, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/alarm_control_panel/__init__.py", line 316, in async_handle_alarm_arm_away
    await self.async_alarm_arm_away(self.check_code_arm_required(code))
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/alarm_control_panel/__init__.py", line 277, in check_code_arm_required
    raise ServiceValidationError(
homeassistant.exceptions.ServiceValidationError: Arming requires a code but none was given for alarm_control_panel.jablotron_ja_100_byt_komplet`

**Comment by JakubBW** [comment]
I have checked older versions and I have the same problem ;/

**Comment by Pigotka** [comment]
@JakubBW Hello, I've check the issue. The problem in your log is that yout Jablotron Arm service requires a arm code but you did not provide any. I don't know how Apple Home interface looks like so tell me. Did you enter a code when requesting arm through Apple Home? If not what do you expect then?

In HA interface the UI would prompt you for the code.

**Comment by Faasteer** [comment]
> @JakubBW Hello, I've check the issue. The problem in your log is that yout Jablotron Arm service requires a arm code but you did not provide any. I don't know how Apple Home interface looks like so tell me. Did you enter a code when requesting arm through Apple Home? If not what do you expect then?
> 
> In HA interface the UI would prompt you for the code.

Hey,
I'm not JakubBW, but since I'm dealing with the same problem, I'll try to answer. Apple Home doesn't ask for a PIN and never has. In the past it worked like this without any problems, but now we are getting this error. 

I believe the PIN used before was one that is set directly during device configuration, as seen in the picture below. But I'm not a programmer, so I could be wrong. Even within the HomeAssistant UI, it used to work without a PIN - but that doesn't bother me because it can ask for one. 

![image](https://github.com/user-attachments/assets/6db7cbaa-e5f0-47b3-ae00-7a3cd5742bed)


Thank you.

**Comment by Pigotka** [comment]
Alright thank you now I understand the problem. Since Apple Home is not providing the code HA automatically fails on missing code. I can intercept and fix that.

**Comment by Faasteer** [comment]
That would be great! I really appreciate your work and the time you are giving to this integration. Thank you for that.

**Comment by Pigotka** [comment]
@Faasteer can you check 0.6.7 release? I rewrote the alarm to support default HA codes. You can find it now in alarm entity settings instead of integration setup.

**Comment by Faasteer** [comment]
You are the BEST!!! 😍 I just tried it and it works like a charm.

I can't tell you how happy you made me (and my wife) with this fix.

Thank you so much. 👍
